project:
  type: website
  render:
    - "*.qmd"
    - "!Take-home_Ex1_Test.qmd"
    - "!Take-home_Ex1_Test2.qmd"
    - "!Take-home_Ex1_Test*.qmd"
    
website:
  title: "ISSS624"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1a
            href: Hands-on_Ex/Hands-on_Ex1a/Hands-on_Ex1a.html
          - text: Hands-on Exercise 1b
            href: Hands-on_Ex/Hands-on_Ex1b/Hands-on_Ex1b.html
          - text: Hands-on Exercise 2a
            href: Hands-on_Ex/Hands-on_Ex2a/Hands-on_Ex2a.html
          - text: Hands-on Exercise 2b
            href: Hands-on_Ex/Hands-on_Ex2b/Hands-on_Ex2b.html
          - text: Hands-on Exercise 2c
            href: Hands-on_Ex/Hands-on_Ex2c/Hands-on_Ex2c.html
          - text: Hands-on Exercise 3
            href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.html
            
      - text: In-class Exercise
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
          - text: In-class Exercise 2
            href: In-class_Ex/In-class_Ex2/In-class_Ex2.html
            
      - text: Take-home Exercise
        menu: 
          - text: Take-home Exercise 1
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html
          - text: Take-home Exercise 2
            href: Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html
            
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

